# coding: utf-8

"""
    LUSID API

    FINBOURNE Technology  # noqa: E501

    The version of the OpenAPI document: 1.1.151
    Contact: info@finbourne.com
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from lusid.configuration import Configuration


class FeeAccrual(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
      required_map (dict): The key is attribute name
                           and the value is whether it is 'required' or 'optional'.
    """
    openapi_types = {
        'name': 'str',
        'calculation_base': 'float',
        'amount': 'float',
        'previous_accrual': 'float',
        'total_accrual': 'float'
    }

    attribute_map = {
        'name': 'name',
        'calculation_base': 'calculationBase',
        'amount': 'amount',
        'previous_accrual': 'previousAccrual',
        'total_accrual': 'totalAccrual'
    }

    required_map = {
        'name': 'optional',
        'calculation_base': 'optional',
        'amount': 'optional',
        'previous_accrual': 'optional',
        'total_accrual': 'optional'
    }

    def __init__(self, name=None, calculation_base=None, amount=None, previous_accrual=None, total_accrual=None, local_vars_configuration=None):  # noqa: E501
        """FeeAccrual - a model defined in OpenAPI"
        
        :param name: 
        :type name: str
        :param calculation_base: 
        :type calculation_base: float
        :param amount: 
        :type amount: float
        :param previous_accrual: 
        :type previous_accrual: float
        :param total_accrual: 
        :type total_accrual: float

        """  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._calculation_base = None
        self._amount = None
        self._previous_accrual = None
        self._total_accrual = None
        self.discriminator = None

        self.name = name
        if calculation_base is not None:
            self.calculation_base = calculation_base
        if amount is not None:
            self.amount = amount
        if previous_accrual is not None:
            self.previous_accrual = previous_accrual
        if total_accrual is not None:
            self.total_accrual = total_accrual

    @property
    def name(self):
        """Gets the name of this FeeAccrual.  # noqa: E501


        :return: The name of this FeeAccrual.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FeeAccrual.


        :param name: The name of this FeeAccrual.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def calculation_base(self):
        """Gets the calculation_base of this FeeAccrual.  # noqa: E501


        :return: The calculation_base of this FeeAccrual.  # noqa: E501
        :rtype: float
        """
        return self._calculation_base

    @calculation_base.setter
    def calculation_base(self, calculation_base):
        """Sets the calculation_base of this FeeAccrual.


        :param calculation_base: The calculation_base of this FeeAccrual.  # noqa: E501
        :type calculation_base: float
        """

        self._calculation_base = calculation_base

    @property
    def amount(self):
        """Gets the amount of this FeeAccrual.  # noqa: E501


        :return: The amount of this FeeAccrual.  # noqa: E501
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this FeeAccrual.


        :param amount: The amount of this FeeAccrual.  # noqa: E501
        :type amount: float
        """

        self._amount = amount

    @property
    def previous_accrual(self):
        """Gets the previous_accrual of this FeeAccrual.  # noqa: E501


        :return: The previous_accrual of this FeeAccrual.  # noqa: E501
        :rtype: float
        """
        return self._previous_accrual

    @previous_accrual.setter
    def previous_accrual(self, previous_accrual):
        """Sets the previous_accrual of this FeeAccrual.


        :param previous_accrual: The previous_accrual of this FeeAccrual.  # noqa: E501
        :type previous_accrual: float
        """

        self._previous_accrual = previous_accrual

    @property
    def total_accrual(self):
        """Gets the total_accrual of this FeeAccrual.  # noqa: E501


        :return: The total_accrual of this FeeAccrual.  # noqa: E501
        :rtype: float
        """
        return self._total_accrual

    @total_accrual.setter
    def total_accrual(self, total_accrual):
        """Sets the total_accrual of this FeeAccrual.


        :param total_accrual: The total_accrual of this FeeAccrual.  # noqa: E501
        :type total_accrual: float
        """

        self._total_accrual = total_accrual

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FeeAccrual):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FeeAccrual):
            return True

        return self.to_dict() != other.to_dict()
